name: Publish to Comfy Registry

on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-node:
    if: ${{ github.repository_owner == 'Rona1do' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Publish custom node
        uses: Comfy-Org/publish-node-action@v1
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
